# Generated by Django 4.2.5 on 2023-09-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reccomender', '0004_mylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='desc',
            field=models.TextField(max_length=600),
        ),
    ]
