# Generated by Django 4.2.5 on 2024-02-28 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reccomender', '0008_movie_rating_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='commnet',
            new_name='comment',
        ),
    ]
