# Generated by Django 4.2.5 on 2024-02-28 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reccomender', '0009_rename_commnet_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
