# Generated by Django 4.2.4 on 2024-03-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reccomender', '0010_comments_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='lang',
            field=models.CharField(max_length=50),
        ),
    ]
